### ISSUE TITLE
RBSE Back to Basics

### ISSUE THREAD

**Issue by ImportTaste** [LoonyLadle/LuluAnimalCybernetics#7]
There is a version of RBSE that strips down the original significantly that I've taken a liking to. It's called RBSE Back to Basics and it's maintained [here](https://github.com/troopersmith1/RBSEBackToBasics1.1). Judging by the more detailed description on the [workshop page](https://steamcommunity.com/sharedfiles/filedetails/?id=2040569399), I strongly suspect it makes some alterations that conflict or otherwise don't mesh quite as well as the original RBSE does with your mod... however it's difficult for me to tell without taking a great deal of time to examine many XML files I've yet to familiarize myself with.

Does this require any special treatment, and if so, could you adjust for it?

**Comment by LoonyLadle** [comment]
Trunken was the one who did many of the compatibility+integration patches for other mods. I can have a look but this would be an extremely low priority task.

**Comment by LoonyLadle** [comment]
With the radical redesign in version 2.0.0 of this mod, compatibility patches are no longer required!
